name: "Manifest Builder"
description: "Build Manifest for Deployments"
inputs:
  groupId:
    required: true
  artifactId:
    required: true
  version:
    required: true
  commitSHA:
    required: true
  outputFile:
    required: false
    default: "manifest.json"
output:
  manifestFile:
    description: "Path to manifest file"
runs:
  using: "node16"
  main: "index.js"